### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by jay-hennen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jay-hennen** [comment]
@conda-forge-admin, please rerender

**Comment by jay-hennen** [comment]
What the heck is the CI failure? Looks like a misconfiguration...

**Comment by ChrisBarker-NOAA** [comment]
Weird -- though I think I saw somethign about a too-long filename when runing the tests.

conda-build does put a lot of "placeholder/[placeholder..." in filenames so that they are long enough to be replaced when installed, so that might have hit a limit -- but why hadn't it hit it before?!?

However, ot does look like it's failing when running the pytests -- perhaps there is no need to run the full test suite in conda-build at all -- as a rule, we're trying to test the conda package, not the code itself -- that should have already been done :-)

It might be good to have a minimal set of tests beyond importing that do test the build -- but for now, maybe just comment that out and see what happens.

**Comment by ChrisBarker-NOAA** [comment]
OK -- I just ran the gridded tests from source -- same errors.

We need to go fix the code / tests before pushing the package.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- the CI tests on github look like they are passing -- but they haven't run in 2 years :-(

I'll go take a look

**Comment by jay-hennen** [comment]
Go figure. The 'problems' I discovered and fixed when writing the new tests broke a bunch of other tests. I'll get these resolved...

**Pull request closed without merging**
